### ISSUE TITLE
get_the_post_thumbnail on static html

### ISSUE THREAD

**Issue by MaximeCulea** [BeAPI/prod-images#1]
In static html, the method get_the_post_thumbnail doesn't work. The generated assets link seems broken.

**Comment by herewithme** [comment]
@MaximeCulea If you're talking about HTML mockups created by our front-end developers, yes that's not compatible, and I do not think it can be, since we only emulate 2-3 PHP functions in HTML templates.

**Comment by MaximeCulea** [comment]
Yeap ! So maybe we could use the same func name if not defined to not broke the html ?

**Comment by asadowski10** [comment]
Not applicable in open source project

Thanks
