### ISSUE TITLE
leaving .htaccess when multisite

### ISSUE THREAD

**Issue by ghost** [BeAPI/prod-images#7]
Currently we have to add a line in .htaccess when it's a multisite installation, is it possible to handle this directly in PHP ? cause it's not very handy when deploying.

**Comment by herewithme** [comment]
Unless I'm mistaken, it's not possible. But we should continue to search.

**Comment by Rahe** [comment]
Can be handled with function `insert_with_markers`

**Comment by herewithme** [comment]
The rule must be added quite precisely between 2 lines. In short, to explore in R & D.

**Comment by ghost** [comment]
I don't understand why it's impossible ?

**Comment by herewithme** [comment]
It's a little old, I do not remember everything, and as I have not structured the development process, I do not have a recipe book to remember.

To continue in R & D

**Comment by ghost** [comment]
ok

**Comment by herewithme** [comment]
Thank you for the proposal, but not desired as evolution.
